cmake_minimum_required(VERSION 3.22)
project(mirath_tcith_all C ASM)

add_subdirectory(mirath_tcith/mirath_tcith_1a_fast)
add_subdirectory(mirath_tcith/mirath_tcith_1b_fast)
add_subdirectory(mirath_tcith/mirath_tcith_1a_short)
add_subdirectory(mirath_tcith/mirath_tcith_1b_short)
add_subdirectory(mirath_tcith/mirath_tcith_3a_fast)
add_subdirectory(mirath_tcith/mirath_tcith_3b_fast)
add_subdirectory(mirath_tcith/mirath_tcith_3a_short)
add_subdirectory(mirath_tcith/mirath_tcith_3b_short)
add_subdirectory(mirath_tcith/mirath_tcith_5a_fast)
add_subdirectory(mirath_tcith/mirath_tcith_5b_fast)
add_subdirectory(mirath_tcith/mirath_tcith_5a_short)
add_subdirectory(mirath_tcith/mirath_tcith_5b_short)
